D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli"
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Vedrina.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Fouren.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Dedraks.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Virovsko.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Hotnitsa.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Staropatitsa.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Yassen.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Vurbitsa_Vratsa.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Bukovets.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Gorovo.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Vurbitsa_Pleven.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Gougoutka.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Kozloduy_NPP.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Gorno_Negushevo.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Bultime.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Masterhaus_Ravda.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Masterhaus_Primorsko.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Milchev.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Amer_Sport.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Brushlen.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Raklinovo.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Euro07.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Sport_Club_Management.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Atik_Plovdiv.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Agroelit_Buinovo.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Metal_Trade_Vitanovtsi.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Bulgartabak.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Iskur_Lake.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Samuil.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Initialise Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Kaufland_Dupnitsa.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Exit Procedure.sikuli" 
 & D:\Installs\SikuliX\runsikulix.cmd -r "D:\Repeaters\Repeater SnapShotter\Sikuli Scripts\Check Procedure.sikuli"
 
 
